<div id="view-content">
	<div class="row">
		<div class="col-md-12">
			<div class="table-responsive">
    			<table class="table table-striped table-striped table-striped">
                  <caption>我的荤菜</caption>
                  <thead>
                    <tr>
                      <th>序号</th>
                      <th>菜名</th>
                    </tr>
                  </thead>
                  <tbody>
                  <?php 
                  foreach ($this->list as $index=>$huncai) {
                    $index = $index + 1;
                    echo "<tr>
                      <td>{$index}</td>
                      <td>{$huncai['name']}</td>
                    </tr>";
                  }
                  ?>
                  </tbody>
                </table>
			</div>
			<div class="">
				<a class="btn btn-success" href="<?php echo $this->baseUrl("/huncai/add");?>"><i class="glyphicon glyphicon-plus"></i></a>
			</div>
		</div>
	</div>
</div>